## ATIVIDADE

Implementar uma função que dado um sistema linear retorne a solução.
- Método de eliminação de Gauss com pivotação parcial 
- Usar as matrizes elementares

### Função de Resolução

In [16]:
import numpy as np

def sistema_gauss(matriz_aumentada):
    num_equacoes = matriz_aumentada.shape[0]  # número de equações (e variáveis)
    
    if matriz_aumentada.shape[1] != num_equacoes + 1:
        raise ValueError("A matriz aumentada deve ter 'n' linhas e 'n+1' colunas.")

    matriz = matriz_aumentada.astype(float)

    for coluna_pivo in range(num_equacoes):
        # encontrar a linha do pivô 
        linha_pivo_atual = coluna_pivo
        for i in range(coluna_pivo + 1, num_equacoes):
            if abs(matriz[i, coluna_pivo]) > abs(matriz[linha_pivo_atual, coluna_pivo]):
                linha_pivo_atual = i

        # trocar a linha atual (coluna_pivo) pela linha do pivô 
        matriz[[coluna_pivo, linha_pivo_atual]] = matriz[[linha_pivo_atual, coluna_pivo]]

        # verificar se o elemento pivô é zero após a troca 
        if matriz[coluna_pivo, coluna_pivo] == 0:
            print(f"O sistema não possui solução única (matriz singular ou próxima a singular) na coluna {coluna_pivo}.")
            return None

        # eliminar os elementos abaixo do pivô na coluna atual
        for i in range(coluna_pivo + 1, num_equacoes):
            fator = matriz[i, coluna_pivo] / matriz[coluna_pivo, coluna_pivo]

            matriz[i, coluna_pivo:] -= fator * matriz[coluna_pivo, coluna_pivo:]

    vetor_solucao = np.zeros(num_equacoes) 

    for i in range(num_equacoes - 1, -1, -1): 
        if matriz[i, i] == 0:
            print(f"O sistema não possui solução única (elemento diagonal zero na linha {i}).")
            return None
        vetor_solucao[i] = (matriz[i, num_equacoes] - np.dot(matriz[i, i+1:num_equacoes], vetor_solucao[i+1:num_equacoes])) / matriz[i, i]

    return vetor_solucao

### Exemplo 1

In [21]:
print("--- Exemplo 1 ---")

matriz_aumentada_ex1 = np.array([
    [-2, 3, 1, 5, 2],
    [5, 1, -1, 0, -1],
    [1, 6, 3, -1, 0],
    [4, 5, 2, 8, 6]
])

solucao_ex1 = sistema_gauss(matriz_aumentada_ex1)
print("Solução para o Exemplo 1:")
print(solucao_ex1)


--- Exemplo 1 ---
Solução para o Exemplo 1:
[ 0.31421446 -0.81795511  1.75311721  0.66583541]


### Exemplo 2

In [24]:
print("\n--- Exemplo 2 ---")
matriz_aumentada_ex2 = np.array([
    [0,  1,  3,  2,  4, 3],
    [8, -2,  9,  -1,  2, -5],
    [5,  1,  1,  7,  2, 6],
    [-2,  4,  5,  1,  0, -1],
    [7,  -3,  2,  -4,  1, 8]
])

solucao_ex2 = sistema_gauss(matriz_aumentada_ex2)

print("Solução para o Exemplo 2:")
print(solucao_ex2)


--- Exemplo 2 ---
Solução para o Exemplo 2:
[ 2.34749499  4.35430862 -2.39078156 -1.76833667  2.33867735]


### Conferindo o resultado com o Linalg

In [26]:
matriz_ex1 = np.array([
    [-2, 3, 1, 5],
    [5, 1, -1, 0],
    [1, 6, 3, -1],
    [4, 5, 2, 8]
])

solucao_1 = np.array([2, -1, 0, 6])
solucao_linalg1 = np.linalg.solve(matriz_ex1, solucao_1)
print(solucao_linalg1)

matriz_ex2 = np.array([
    [0,  1,  3,  2,  4],
    [8, -2,  9,  -1,  2],
    [5,  1,  1,  7,  2],
    [-2,  4,  5,  1,  0],
    [7,  -3,  2,  -4,  1]
])
solucao_2 = np.array([3, -5, 6, -1, 8])
solucao_linalg2 = np.linalg.solve(matriz_ex2, solucao_2)
print(solucao_linalg2)

[ 0.31421446 -0.81795511  1.75311721  0.66583541]
[ 2.34749499  4.35430862 -2.39078156 -1.76833667  2.33867735]
