In [2]:
import MariaClaraMiguel as meuhelp
import numpy as np

---

In [3]:
#diferenças dividas + avalia newton
# Calcula o polinômio interpolador de Newton e o avalia no ponto x=3.
# Você fornece pontos (x, y) e precisa interpolar em um ponto específico com Newton.

x = np.array([1, 2, 4])
y = np.array([1, 4, 16])
coef = meuhelp.diferencas_divididas(x, y)
valor = meuhelp.avalia_newton(x, 3, coef)

Tabela de Diferenças Divididas:
[[ 1.  3.  1.]
 [ 4.  6.  0.]
 [16.  0.  0.]]
O valor do polinômio de Newton em x = 3 é 9.0


---

In [8]:
# polinomio_lagrage
# Calcula o valor do polinômio interpolador de Lagrande no ponto x = 3
# Comparar resultados entre Newton e Lagrange ou justificar a escolha de método.

x = np.array([1, 2, 4])
y = np.array([1, 4, 16])
x_ponto = 3

# Newton
coef = meuhelp.diferencas_divididas(x, y)
valor_newton = meuhelp.avalia_newton(x, x_ponto, coef)

# Lagrange
valor_lagrange = meuhelp.polinomio_lagrange(x, y, x_ponto)

print(f"Newton: {valor_newton}, Lagrange: {valor_lagrange}")

Tabela de Diferenças Divididas:
[[ 1.  3.  1.]
 [ 4.  6.  0.]
 [16.  0.  0.]]
O valor do polinômio de Newton em x = 3 é 9.0
O valor do polinômio de Lagrange em x = 3 é 9.0
Newton: 9.0, Lagrange: 9.0


In [ ]:
# Usei o método de Newton porque ele permite reutilizar os coeficientes para múltiplas interpolações 
# com o mesmo conjunto de dados, o que é mais eficiente computacionalmente. 
# Além disso, se novos pontos forem adicionados, é possível atualizar a tabela sem recalcular tudo."

# Usei Lagrange por ser mais direto e rápido de implementar para uma única interpolação. 
# Como só preciso do valor no ponto x=3, não compensa montar toda a tabela de Newton.

---

In [9]:
# eliminação de Gauss + substituição reversa
# resolve um sistema linear Ax = b por eliminação de Gauss.
# Resolver sistema via Gauss, mostrar matriz triangular e solução.

A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])
b = np.array([8, -11, -3])
A_tri, b_mod = meuhelp.eliminacao_gauss(A, b)
x = meuhelp.substituicao_reversa(A_tri, b_mod)

Matriz após Eliminação de Gauss:
[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]
Vetor de termos independentes atualizado:
[8. 1. 1.]
Solução do sistema via substituição reversa:
[ 2.  3. -1.]


---

In [11]:
# decomposicao_LU + sistemas_triangularesInferior + sistema_triangular_superior
# Resolve o sistema Ax = b via decomposição LU (Doolittle).
# Executar LU e resolver o sistema via dois sistemas triangulares.

A = np.array([[2, -1, -2],
              [-4, 6, 3],
              [-4, -2, 8]])
b = np.array([-2, 9, -5])
L, U = meuhelp.decomposicao_LU(A)
y = meuhelp.sistemas_triangularesInferior(L, b)
x = meuhelp.sistema_triangular_superior(U, y)

Matriz L:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]
Matriz U:
[[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  3.]]


--- 

In [15]:
# cholesky + sistemas_triangularesInferior + sistema_triangular_superior
# Usa decomposição de Cholesky para resolver sistema com matriz simétrica e definida positiva.
# Aplicar Cholesky e resolver o sistema. Pode ser pedido para validar se a matriz é definida positiva.

A = np.array([[4, 2],
              [2, 3]])
b = np.array([6, 7])

resp = meuhelp.definida_positiva_por_cholesky(A)
print(resp)

L = meuhelp.cholesky(A)
y = meuhelp.sistemas_triangularesInferior(L, b)
x = meuhelp.sistema_triangular_superior(L.T, y)

Matriz L da decomposição de Cholesky:
[[2 0]
 [1 1]]
A matriz é definida positiva (Cholesky válida).
True
Matriz L da decomposição de Cholesky:
[[2 0]
 [1 1]]


---

In [ ]:
# integral_trapezio
# Aproxima a integral de x^2 de 0 a 2 com 4 subintervalos (método do trapézio composto).
# Implementar ou aplicar a regra do trapézio com um número dado de subintervalos.

def f(x):
    return x**2

resultado = meuhelp.integral_trapezio(f, 0, 2, 4)

Integral aproximada pelo método do trapézio em [0, 2] com 4 subintervalos: 2.75


In [20]:
# integral_simpson
# Aproxima a integral de x^2 de 0 a 2 com 4 subintervalos (método de Simpson 1/3).
# Calcular a integral com n par. Pode cobrar validação do número de subintervalos.

def f(x):
    return x**2

resultado = meuhelp.integral_simpson(f, 0, 2, 4)

# Validei que n é par antes de aplicar Simpson, pois o método depende de pares de subintervalos 
# para funcionar corretamente. 
# Caso n seja ímpar, levanto um erro para evitar cálculo incorreto.

Integral aproximada pelo método de Simpson em [0, 2] com 4 subintervalos: 2.6666666666666665


--- 

In [19]:
# calcular_determinante
# Calcula o determinante de uma matriz quadrada usando eliminação.
# Determinar se a matriz é singular (det=0) ou não.

A = np.array([[2, 3], [1, 4]])
det = meuhelp.calcular_determinante(A)
