## Polinomio Lagrange

In [ ]:
import math

def polinomio_lagrange(pontos_x, pontos_y, x_desejado):
    """
    Calcula o valor do Polinômio de Lagrange em um dado ponto x_desejado e o imprime.

    Parâmetros:
    pontos_x (list): Uma lista dos valores x dos pontos de dados (x0, x1, ..., xn).
    pontos_y (list): Uma lista dos valores y dos pontos de dados (y0, y1, ..., yn).
    x_desejado (float/int): O valor de x no qual o polinômio de Lagrange será avaliado.

    A função imprime o resultado diretamente ou uma mensagem de erro.
    """
    n_pontos = len(pontos_x)

    if n_pontos != len(pontos_y):
        print("Erro: O número de pontos 'x' e 'y' deve ser o mesmo.")
        return

    if len(set(pontos_x)) != n_pontos:
        print("Erro: Os valores de 'x' devem ser distintos para a interpolação de Lagrange.")
        return

    valor_polinomio = 0.0

    for j in range(n_pontos):
        termo_lj = 1.0
            
        for k in range(n_pontos):
            if k != j:
                denominador = pontos_x[j] - pontos_x[k]
                    
                if denominador == 0:
                    print(f"Erro: Divisão por zero detectada ao calcular L_{j}(x). "
                            f"Verifique se há pontos x duplicados: x_{j}={pontos_x[j]}, x_{k}={pontos_x[k]}.")
                    return
                                            
                termo_lj *= (x_desejado - pontos_x[k]) / denominador
            
        valor_polinomio += pontos_y[j] * termo_lj

    print(f"O valor do Polinômio de Lagrange em x = {x_desejado} é: {valor_polinomio:.4f}")

In [2]:
print("--- Exemplo 1: Polinômio de Lagrange com 3 pontos ---")
x_dados_ex1 = [1, 2, 4]
y_dados_ex1 = [3, 5, 10]

print(f"Avaliando o polinômio para os pontos x: {x_dados_ex1} e y: {y_dados_ex1}")

polinomio_lagrange(x_dados_ex1, y_dados_ex1, 1.0)
polinomio_lagrange(x_dados_ex1, y_dados_ex1, 2.0)
polinomio_lagrange(x_dados_ex1, y_dados_ex1, 3.0)
polinomio_lagrange(x_dados_ex1, y_dados_ex1, 4.0)
polinomio_lagrange(x_dados_ex1, y_dados_ex1, 0.0)

--- Exemplo 1: Polinômio de Lagrange com 3 pontos ---
Avaliando o polinômio para os pontos x: [1, 2, 4] e y: [3, 5, 10]
O valor do Polinômio de Lagrange em x = 1.0 é: 3.0000
O valor do Polinômio de Lagrange em x = 2.0 é: 5.0000
O valor do Polinômio de Lagrange em x = 3.0 é: 7.3333
O valor do Polinômio de Lagrange em x = 4.0 é: 10.0000
O valor do Polinômio de Lagrange em x = 0.0 é: 1.3333


## Polinomio Interpolador de Newton

In [6]:
def polinomio_interpolador_newton(pontos_x, pontos_y, x_desejado):
    """
    Calcula o valor do polinômio interpolador de Newton em um dado ponto x_desejado
    e imprime o resultado.

    Parâmetros:
    pontos_x (list): Uma lista dos valores x dos pontos de dados (x0, x1, ..., xn).
    pontos_y (list): Uma lista dos valores y dos pontos de dados (y0, y1, ..., yn).
    x_desejado (float/int): O valor de x no qual o polinômio será avaliado.

    A função imprime o resultado diretamente ou uma mensagem de erro.
    """
    n_pontos = len(pontos_x)

    if n_pontos != len(pontos_y):
        print("Erro: O número de pontos 'x' e 'y' deve ser o mesmo.")
        return

    if len(set(pontos_x)) != n_pontos:
        print("Erro: Os valores de 'x' devem ser distintos para a interpolação.")
        return

    tabela_diferencas = [[0.0] * n_pontos for _ in range(n_pontos)]
        
    for i in range(n_pontos):
        tabela_diferencas[i][0] = pontos_y[i]

    for coluna in range(1, n_pontos): # Itera pelas colunas (ordens das diferenças)
        for linha in range(n_pontos - coluna): # Itera pelas linhas da coluna atual
            numerador = tabela_diferencas[linha + 1][coluna - 1] - tabela_diferencas[linha][coluna - 1]
            denominador = pontos_x[linha + coluna] - pontos_x[linha]
                
            if denominador == 0:
                print(f"Erro: Divisão por zero detectada ao calcular diferença dividida. "
                        f"Verifique seus pontos de dados.")
                return

            tabela_diferencas[linha][coluna] = numerador / denominador

        coeficientes = [tabela_diferencas[0][coluna] for coluna in range(n_pontos)]

        valor_polinomio = coeficientes[0] # Começa com o termo f[x0]
        
    for i in range(1, n_pontos):
        termo_produto = coeficientes[i]
        for k in range(i):
            termo_produto *= (x_desejado - pontos_x[k])
        valor_polinomio += termo_produto

    print(f"O valor do Polinômio de Newton em x = {x_desejado} é: {valor_polinomio:.4f}")

In [7]:

print("--- Exemplo 1: Polinômio de Newton com 3 pontos ---")
# Pontos do exemplo: (1,3), (2,5), (4,10)
x_dados_ex1 = [1, 2, 4]
y_dados_ex1 = [3, 5, 10]

print(f"Avaliando o polinômio para os pontos x: {x_dados_ex1} e y: {y_dados_ex1}")

# Testando em pontos conhecidos (devem retornar o valor y original)
polinomio_interpolador_newton(x_dados_ex1, y_dados_ex1, 1.0) # Esperado: 3.0
polinomio_interpolador_newton(x_dados_ex1, y_dados_ex1, 2.0) # Esperado: 5.0
polinomio_interpolador_newton(x_dados_ex1, y_dados_ex1, 4.0) # Esperado: 10.0

--- Exemplo 1: Polinômio de Newton com 3 pontos ---
Avaliando o polinômio para os pontos x: [1, 2, 4] e y: [3, 5, 10]
O valor do Polinômio de Newton em x = 1.0 é: 3.0000
O valor do Polinômio de Newton em x = 2.0 é: 5.0000
O valor do Polinômio de Newton em x = 4.0 é: 10.0000


## Sistema Gauss

In [23]:
import numpy as np

def sistema_gauss(matriz_coeficientes, vetor_termos_independentes):
    """
    Resolve um sistema de equações lineares usando o método da Eliminação de Gauss
    e imprime a solução.

    Parâmetros:
    matriz_coeficientes (list of lists): A matriz dos coeficientes do sistema (matriz A).
    vetor_termos_independentes (list): O vetor dos termos independentes (vetor b).

    A função imprime a solução do sistema ou uma mensagem de erro.
    """
    A = np.array(matriz_coeficientes, dtype=float)
    b = np.array(vetor_termos_independentes, dtype=float)

    numero_equacoes = A.shape[0]
    numero_variaveis = A.shape[1]

    if numero_equacoes != len(b):
        print("Erro: O número de equações deve ser igual ao número de termos independentes.")
        return
    if numero_equacoes != numero_variaveis:
        print("Aviso: A matriz de coeficientes não é quadrada. Este algoritmo pode não funcionar como esperado.")
        
    matriz_aumentada = np.c_[A, b]
        
    print("--- Matriz Aumentada Inicial ---")
    print(np.array_str(matriz_aumentada, precision=4, suppress_small=True))
    print("-" * 30)

    for i in range(numero_equacoes): # Percorre as linhas para definir o pivô
        pivo_max_idx = i
        for k in range(i + 1, numero_equacoes):
            if abs(matriz_aumentada[k, i]) > abs(matriz_aumentada[pivo_max_idx, i]):
                pivo_max_idx = k
            
            # Trocar a linha atual com a linha do pivô máximo, se necessário
        if pivo_max_idx != i:
            matriz_aumentada[[i, pivo_max_idx]] = matriz_aumentada[[pivo_max_idx, i]]
            print(f"Troca de linhas: L{i+1} <-> L{pivo_max_idx+1}")
            print(np.array_str(matriz_aumentada, precision=4, suppress_small=True))
            print("-" * 30)

            # Verificar se o pivô é zero (sistema pode não ter solução única ou ser singular)
        if matriz_aumentada[i, i] == 0:
            print(f"Erro: O pivô na linha {i+1}, coluna {i+1} é zero.")
            print("O sistema pode não ter solução única, ter infinitas soluções ou nenhuma solução.")
            return

            # Zerar os elementos abaixo do pivô na coluna atual
        for j in range(i + 1, numero_equacoes): # Percorre as linhas abaixo do pivô
            fator = matriz_aumentada[j, i] / matriz_aumentada[i, i]
            matriz_aumentada[j, :] = matriz_aumentada[j, :] - fator * matriz_aumentada[i, :]

        print("--- Matriz Aumentada Escalonada (Triangular Superior) ---")
        print(np.array_str(matriz_aumentada, precision=4, suppress_small=True))
        print("-" * 30)

        solucoes = np.zeros(numero_variaveis) # Vetor para armazenar as soluções

        for i in range(numero_equacoes - 1, -1, -1): # Percorre as equações de baixo para cima
            termo_constante = matriz_aumentada[i, numero_variaveis]
            
            soma_conhecidos = 0
            for j in range(i + 1, numero_variaveis):
                soma_conhecidos += matriz_aumentada[i, j] * solucoes[j]
            
            solucoes[i] = (termo_constante - soma_conhecidos) / matriz_aumentada[i, i]

        print("\n--- Solução do Sistema ---")
        for i in range(numero_variaveis):
            print(f"x_{i+1} = {solucoes[i]:.6f}")

In [24]:

print("### Exemplo 1: Sistema com Solução Única ###")
# Sistema:
# x1 + 2x2 + x3 = 8
# 2x1 + x2 - x3 = 1
# x1 - x2 + 2x3 = 7
# Solução esperada: x1=1.5, x2=1.5, x3=3.5
sistema_gauss(
    matriz_coeficientes=[[1, 2, 1], [2, 1, -1], [1, -1, 2]],
    vetor_termos_independentes=[8, 1, 7]
)

### Exemplo 1: Sistema com Solução Única ###
--- Matriz Aumentada Inicial ---
[[ 1.  2.  1.  8.]
 [ 2.  1. -1.  1.]
 [ 1. -1.  2.  7.]]
------------------------------
Troca de linhas: L1 <-> L2
[[ 2.  1. -1.  1.]
 [ 1.  2.  1.  8.]
 [ 1. -1.  2.  7.]]
------------------------------
--- Matriz Aumentada Escalonada (Triangular Superior) ---
[[ 2.   1.  -1.   1. ]
 [ 0.   1.5  1.5  7.5]
 [ 0.  -1.5  2.5  6.5]]
------------------------------

--- Solução do Sistema ---
x_1 = 0.600000
x_2 = 2.400000
x_3 = 2.600000
--- Matriz Aumentada Escalonada (Triangular Superior) ---
[[ 2.   1.  -1.   1. ]
 [ 0.   1.5  1.5  7.5]
 [ 0.   0.   4.  14. ]]
------------------------------

--- Solução do Sistema ---
x_1 = 1.500000
x_2 = 1.500000
x_3 = 3.500000
--- Matriz Aumentada Escalonada (Triangular Superior) ---
[[ 2.   1.  -1.   1. ]
 [ 0.   1.5  1.5  7.5]
 [ 0.   0.   4.  14. ]]
------------------------------

--- Solução do Sistema ---
x_1 = 1.500000
x_2 = 1.500000
x_3 = 3.500000


## Decomposição LU

In [19]:
import numpy as np

def decomposicao_lu(matriz_a, vetor_b):

    dimensao = matriz_a.shape[0]

    if matriz_a.shape[1] != dimensao:
        print("Erro: A matriz deve ser quadrada.")
        return None
    if vetor_b.shape[0] != dimensao:
        print("Erro: O tamanho do vetor b deve ser igual à dimensão da matriz.")
        return None

    matriz_l = np.eye(dimensao, dtype=float)
    matriz_u = np.copy(matriz_a).astype(float)

    for coluna_pivo in range(dimensao):
        if matriz_u[coluna_pivo, coluna_pivo] == 0:
            print(f"Aviso: Elemento pivô U[{coluna_pivo},{coluna_pivo}] é zero. "
                  "Decomposição LU pode não ser possível sem pivoteamento.")
            return None
        for linha_atual in range(coluna_pivo + 1, dimensao):
            multiplicador = matriz_u[linha_atual, coluna_pivo] / matriz_u[coluna_pivo, coluna_pivo]
            matriz_l[linha_atual, coluna_pivo] = multiplicador
            matriz_u[linha_atual, coluna_pivo:] -= multiplicador * matriz_u[coluna_pivo, coluna_pivo:]
    
    print("Matriz Triangular Inferior L:")
    print(matriz_l)
    print("\nMatriz Triangular Superior U:")
    print(matriz_u)

    vetor_y = np.zeros(dimensao, dtype=float)
    for i in range(dimensao):
        vetor_y[i] = (vetor_b[i] - np.dot(matriz_l[i, :i], vetor_y[:i])) / matriz_l[i, i]

    vetor_x = np.zeros(dimensao, dtype=float)
    for i in range(dimensao - 1, -1, -1):
        if matriz_u[i, i] == 0:
            print(f"Aviso: Elemento pivô U[{i},{i}] é zero durante a substituição regressiva. "
                  "Sistema pode ter múltiplas soluções ou nenhuma.")
            return None
        vetor_x[i] = (vetor_y[i] - np.dot(matriz_u[i, i+1:], vetor_x[i+1:])) / matriz_u[i, i]
    
    print("\nSolução Final")
    print("Vetor Solução x:")
    print(vetor_x)
    print("\nVerificação A @ x (deve ser aproximadamente b):")
    print(matriz_a @ vetor_x)

    return vetor_x

In [21]:
A = np.array([
    [4, -1, 3, 8],
    [1, 6, 2, -3],
    [5, 5, 1, 0],
    [2, 4, -2, 1]
])

b = np.array([43, 7, 8, 8])

solucao = decomposicao_lu(A, b)


Matriz Triangular Inferior L:
[[1.   0.   0.   0.  ]
 [0.25 1.   0.   0.  ]
 [1.25 1.   1.   0.  ]
 [0.5  0.72 1.1  1.  ]]

Matriz Triangular Superior U:
[[ 4.   -1.    3.    8.  ]
 [ 0.    6.25  1.25 -5.  ]
 [ 0.    0.   -4.   -5.  ]
 [ 0.    0.    0.    6.1 ]]

Solução Final
Vetor Solução x:
[-2.44262295  3.39344262  3.24590164  5.80327869]

Verificação A @ x (deve ser aproximadamente b):
[43.  7.  8.  8.]


In [25]:
def sistemas_triangulares(L, C):
    n = L.shape[0]   
    x = np.zeros(n) 

    if L[0, 0] == 0:
        raise ValueError("Elemento L[0,0] é zero, divisão por zero impossível.")
    x[0] = C[0] / L[0, 0]

    for i in range(1, n):
        soma = 0
        for j in range(i):
            soma += L[i, j] * x[j]
        if L[i, i] == 0:
            raise ValueError(f"Elemento L[{i},{i}] é zero, divisão por zero impossível.")
        x[i] = (C[i] - soma) / L[i, i]

    return x

def sistemas_triangularesInferior(L, C):
    n = L.shape[0]   
    x = np.zeros(n) 

    if L[0, 0] == 0:
        raise ValueError("Elemento L[0,0] é zero, divisão por zero impossível.")
    x[0] = C[0] / L[0, 0]

    for i in range(1, n):
        soma = 0
        for j in range(i):
            soma += L[i, j] * x[j]
        if L[i, i] == 0:
            raise ValueError(f"Elemento L[{i},{i}] é zero, divisão por zero impossível.")
        x[i] = (C[i] - soma) / L[i, i]

    return x

def sistema_triangular_superior(U, C):
    n = U.shape[0]  
    x = np.zeros(n) 

    for i in range(n - 2, -1, -1):
        soma = 0

        for j in range(i + 1, n):
            soma += U[i, j] * x[j]

        if U[i, i] == 0:
            raise ValueError(f"Elemento U[{i},{i}] na diagonal é zero, divisão por zero impossível.")
        x[i] = (C[i] - soma) / U[i, i]

    return x

# solucao2 = sistema_triangular_superior(U_exemplo2, C_exemplo2)
# print("A solução do sistema linear triangular superior (x) é:")
# print(solucao2)

## Determinante

In [26]:
def calcular_determinante(matriz_entrada):
    num_linhas, num_colunas = matriz_entrada.shape
    if num_linhas != num_colunas:
        print("Erro: O determinante só pode ser calculado para matrizes quadradas.")
        return None
    
    matriz_temp = matriz_entrada.copy().astype(float)
    
    determinante = 1.0 

    for k in range(num_linhas): 
        elemento_pivo = matriz_temp[k, k]

        if abs(elemento_pivo) < 1e-9: 
            print(f"Aviso: Elemento pivô muito pequeno ou zero na posição ({k}, {k}). "
                  "A matriz pode ser singular (determinante ~ 0).")
            return 0.0 

        determinante *= elemento_pivo 
        for i in range(k + 1, num_linhas):
            fator_multiplicador = matriz_temp[i, k] / elemento_pivo
            
            matriz_temp[i, k:] = matriz_temp[i, k:] - fator_multiplicador * matriz_temp[k, k:]
            
    return determinante

### Interpolador

In [27]:
def integral(func, inferior, superior, n):
    if n <= 0:
        raise ValueError("O número de subintervalos (n) deve ser um inteiro positivo.")

    h = (superior - inferior) / n 
    soma_areas = func(inferior) + func(superior)

    for i in range(1, n):
        x_i = inferior + i * h
        soma_areas += 2 * func(x_i)

    integral_aproximada = (h / 2) * soma_areas

    return integral_aproximada

## Integral pela Regra do Trapézio

In [28]:
def regra_do_trapezio_composta_e_imprimir(funcao_f, limite_inferior_a, limite_superior_b, numero_subintervalos_n):
    """
    Calcula a integral definida de uma função usando a Regra do Trapézio Composta
    e imprime o resultado.

    Parâmetros:
    funcao_f (callable): A função a ser integrada (por exemplo, lambda x: x**2).
    limite_inferior_a (float): O limite inferior do intervalo de integração.
    limite_superior_b (float): O limite superior do intervalo de integração.
    numero_subintervalos_n (int): O número de subintervalos (trapézios) a serem usados.

    A função imprime o valor aproximado da integral ou uma mensagem de erro.
    """
    if numero_subintervalos_n <= 0:
        print("Erro: O número de subintervalos (n) deve ser um inteiro positivo.")
        return
    if limite_inferior_a >= limite_superior_b:
        print("Erro: O limite inferior 'a' deve ser menor que o limite superior 'b'.")
        return

    largura_h = (limite_superior_b - limite_inferior_a) / numero_subintervalos_n

    soma_termos = funcao_f(limite_inferior_a) + funcao_f(limite_superior_b)

    for i in range(1, numero_subintervalos_n):
        ponto_x_i = limite_inferior_a + i * largura_h
        soma_termos += 2 * funcao_f(ponto_x_i)

    resultado_integral = (largura_h / 2) * soma_termos

    print(f"A integral aproximada usando a Regra do Trapézio (N={numero_subintervalos_n}) é: {resultado_integral:.6f}")

In [33]:
def minha_funcao_quadratica(x):
    return x**2

def minha_funcao_seno(x):
    import math
    return math.sin(x)

def minha_funcao_exponencial(x):
    import math
    return math.exp(x)

print("Integral de x^2 de 0 a 2 com N=4 \n")
# Integral exata: 8/3 ≈ 2.666667
regra_do_trapezio_composta_e_imprimir(minha_funcao_quadratica, 0, 2, 4)

print("Exemplo 2: Integral de x^2 de 0 a 2 com N=100 (maior precisão) \n")
regra_do_trapezio_composta_e_imprimir(minha_funcao_quadratica, 0, 2, 100)

print("Exemplo 3: Integral de sen(x) de 0 a PI com N=50 \n")
# Integral exata: -cos(x) de 0 a PI = -(-1) - (-1) = 1 + 1 = 2
import math
regra_do_trapezio_composta_e_imprimir(minha_funcao_seno, 0, math.pi, 50)

print("Exemplo 4: Integral de exp(x) de 0 a 1 com N=10 \n")
# Integral exata: exp(x) de 0 a 1 = e^1 - e^0 = e - 1 ≈ 1.718282
regra_do_trapezio_composta_e_imprimir(minha_funcao_exponencial, 0, 1, 10)


Integral de x^2 de 0 a 2 com N=4 

A integral aproximada usando a Regra do Trapézio (N=4) é: 2.750000
Exemplo 2: Integral de x^2 de 0 a 2 com N=100 (maior precisão) 

A integral aproximada usando a Regra do Trapézio (N=100) é: 2.666800
Exemplo 3: Integral de sen(x) de 0 a PI com N=50 

A integral aproximada usando a Regra do Trapézio (N=50) é: 1.999342
Exemplo 4: Integral de exp(x) de 0 a 1 com N=10 

A integral aproximada usando a Regra do Trapézio (N=10) é: 1.719713
